### ISSUE TITLE
let's make the SIPAuthServe component more powerful

### ISSUE THREAD

**Issue by yosemitebandit** [endaga/openbts-python#3]
in client, we have to jump through a lot of formatting hoops to work with SIPAuthServe.  I think we should provide a few simpler methods for getting delivery receipts, looking up users, etc -- something like:

``` python
import openbts

sip_auth_serve = openbts.components.SIPAuthServe()

sip_auth_serve.update_balance('IMSI000123', '2500')
sip_auth_serve.imsi_from_number('5551234')
sip_auth_serve.numbers_from_imsi('IMSI000123')
```

thoughts @kkroo @shaddi ?

**Comment by yosemitebandit** [comment]
not totally familiar with these tables, but I can take a shot at this if you all think it makes sense.

**Comment by shaddi** [comment]
:+1:

**Comment by kkroo** [comment]
I think this abstraction is needed for sure. this functionality makes sense to have in this package. if we are open sourcing this, i dont think openbts ships with credits stuff.

but this will come in handy with when we build out the `Subscriber` object.

**Comment by kkroo** [comment]
and we can walk through the the entire subscriber registry tables with any confusion that comes up
